"use client"

import './globals.css'

import { MantineProvider } from '@mantine/core';
import {SessionProvider} from "next-auth/react";
import { Notifications } from '@mantine/notifications';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <SessionProvider>
          <MantineProvider>
              <Notifications/>
              <html lang="en">
              <body className="bg-gray-200">{children}</body>
              </html>
          </MantineProvider>
      </SessionProvider>
  )
}
